version: "3"

services:
    proxy:
        image: docker.io/library/nginx:latest
        network_mode: host
        ports:
            - 8000
        volumes:
            - ./dist:/usr/share/nginx/html:z
            - ./nginx.conf:/etc/nginx/nginx.conf:z
